---
development:
  dialect: postgres
  database: tasks-management-with-go_development
  user: root
  password: etu28
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/tasks-management-with-go_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/tasks-management-with-go_production?sslmode=disable"}}
